//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoGaleri.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OtoGaleri.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1 {
            get {
                object obj = ResourceManager.GetObject("1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _10 {
            get {
                object obj = ResourceManager.GetObject("10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _14 {
            get {
                object obj = ResourceManager.GetObject("14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _15 {
            get {
                object obj = ResourceManager.GetObject("15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _151 {
            get {
                object obj = ResourceManager.GetObject("151", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _16 {
            get {
                object obj = ResourceManager.GetObject("16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _17 {
            get {
                object obj = ResourceManager.GetObject("17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _171 {
            get {
                object obj = ResourceManager.GetObject("171", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _22 {
            get {
                object obj = ResourceManager.GetObject("22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _23 {
            get {
                object obj = ResourceManager.GetObject("23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _24 {
            get {
                object obj = ResourceManager.GetObject("24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _25 {
            get {
                object obj = ResourceManager.GetObject("25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _26 {
            get {
                object obj = ResourceManager.GetObject("26", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _27 {
            get {
                object obj = ResourceManager.GetObject("27", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3 {
            get {
                object obj = ResourceManager.GetObject("3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _31 {
            get {
                object obj = ResourceManager.GetObject("31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _32 {
            get {
                object obj = ResourceManager.GetObject("32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4 {
            get {
                object obj = ResourceManager.GetObject("4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5 {
            get {
                object obj = ResourceManager.GetObject("5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7 {
            get {
                object obj = ResourceManager.GetObject("7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8 {
            get {
                object obj = ResourceManager.GetObject("8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _81 {
            get {
                object obj = ResourceManager.GetObject("81", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _9 {
            get {
                object obj = ResourceManager.GetObject("9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__1_ {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__10_ {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (10)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__11_ {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (11)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__12_ {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (12)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__13_ {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (13)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__14_ {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (14)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__15_ {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (15)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__16_ {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (16)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__17_ {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (17)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__19_ {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (19)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__2_ {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__20_ {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (20)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__21_ {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (21)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__22_ {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (22)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__23_ {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (23)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__24_ {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (24)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__25_ {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (25)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__26_ {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (26)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__28_ {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (28)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__29_ {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (29)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__3_ {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (3)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__3_1 {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (3)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__3_2 {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (3)2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__30_ {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (30)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__31_ {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (31)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__32_ {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (32)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__32_1 {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (32)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__33_ {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (33)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__34_ {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (34)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__35_ {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (35)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__36_ {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (36)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__37_ {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (37)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__38_ {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (38)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__39_ {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (39)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__4_ {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (4)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__40_ {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (40)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__41_ {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (41)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__42_ {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (42)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__43_ {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (43)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__44_ {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (44)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__46_ {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (46)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__46_1 {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (46)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__47_ {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (47)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__48_ {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (48)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__49_ {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (49)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__49_1 {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (49)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__5_ {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (5)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__50_ {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (50)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__51_ {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (51)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__52_ {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (52)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__53_ {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (53)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__6_ {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (6)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__6_1 {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (6)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__7_ {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (7)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__7_1 {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (7)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__7_2 {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (7)2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__7_3 {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (7)3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__8_ {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (8)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Colorful_Gradient_Memphis_Disruptive_Brainstorming_Online_Whiteboard__9_ {
            get {
                object obj = ResourceManager.GetObject("Colorful Gradient Memphis Disruptive Brainstorming Online Whiteboard (9)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fvbndn {
            get {
                object obj = ResourceManager.GetObject("fvbndn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GIRIS1 {
            get {
                object obj = ResourceManager.GetObject("GIRIS1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gİRİSkULLANİCİ {
            get {
                object obj = ResourceManager.GetObject("gİRİSkULLANİCİ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap islemler {
            get {
                object obj = ResourceManager.GetObject("islemler", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap İşlemler {
            get {
                object obj = ResourceManager.GetObject("İşlemler", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap KayitOl {
            get {
                object obj = ResourceManager.GetObject("KayitOl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap KayitOl1 {
            get {
                object obj = ResourceManager.GetObject("KayitOl1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Kayitt {
            get {
                object obj = ResourceManager.GetObject("Kayitt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Kayitt1 {
            get {
                object obj = ResourceManager.GetObject("Kayitt1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Kayitt2 {
            get {
                object obj = ResourceManager.GetObject("Kayitt2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap KullaniciGiris {
            get {
                object obj = ResourceManager.GetObject("KullaniciGiris", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap KullaniciGiris1 {
            get {
                object obj = ResourceManager.GetObject("KullaniciGiris1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Sifre_Unuttum {
            get {
                object obj = ResourceManager.GetObject("Sifre Unuttum", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Siyah_ve_Camgöbeği_E_Spor_İllüst {
            get {
                object obj = ResourceManager.GetObject("Siyah ve Camgöbeği E-Spor İllüst", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
